name: CI

on:
  push:
    tags:
      - k[0-9].[0-9]
      - k[0-9].[0-9].[0-9]

jobs:
  kotatogram-desktop:
    runs-on: ubuntu-latest
    name: Build kotatogram-desktop
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: ./
      with:
        package-name: kotatogram-desktop
  kotatogram-desktop-bin:
    runs-on: ubuntu-latest
    name: Build kotatogram-desktop-bin
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: ./
      with:
        package-name: kotatogram-desktop-bin
