name: CI

on:
  push:
    branches:
      - '**'
      - '!upstream'
      - '!upstream/**'

jobs:
  kotatogram-desktop:
    runs-on: ubuntu-latest
    name: Build kotatogram-desktop
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: ./
      with:
        package-name: kotatogram-desktop
